import SideBar from "../components/SideBar";
import { PlusIcon } from "@heroicons/react/24/solid";
import "../styles/globals.css";

export const metadata = {
  title: "ChatGPT Clone",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <div className="bg-[#202321] max-w-xs h-screen overflow-y-auto md:min-w-[15rem]">
            <SideBar />
          </div>

          {/*client provider - notification*/}

          <div className="bg-[#343541] flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
